server:
  port: 8082

spring:
  application:
    name: salary-service

  datasource:
    # Updated to use Aiven connection details:
    url: jdbc:mysql://mysql-salary-service-salary-service.j.aivencloud.com:24151/defaultdb?useSSL=true&requireSSL=true
    username: avnadmin
    password: AVNS_rtIcBq5i6P4O12mQjg2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
